[TEST] surge preview
RIOT-OS/riot-os.org pull request #15
Opened 2021-02-23 16:53 UTC by leandrolanzieri

PR to test #13 using a branch that is from the same repo.

2021-02-23 17:00 UTC, leandrolanzieri commented
>  PR Preview [47b37d1](https://github.com/RIOT-OS/riot-os.org/commit/47b37d175dbdf43fbb0b37952ba6d0cb53e54ef8) has been successfully built and deployed to https://RIOT-OS-riot-os-org-preview-pr-15.surge.sh
> 
>  Build time: **0.019s**
> 
> [<img alt="" width="300" src="https://user-images.githubusercontent.com/507615/90250366-88233900-de6e-11ea-95a5-84f0762ffd39.png">](https://github.com/RIOT-OS/riot-os.org/runs/1963142062)
> 
>  By [surge-preview](https://github.com/afc163/surge-preview)

Sadly we will not be getting this nice comment in PRs coming from forked repos

2021-02-23 17:08 UTC, leandrolanzieri commented
We could use some of @aabadie 's knowledge on actions though :-)

2021-02-23 17:16 UTC, aabadie commented
Seems like there's a lot of duplicated code between the surge action and the deploy action. TBH for this kind of preview, I would prefer Circle CI. But before this, the build workflow must be fixed/simplified or at least discussed somewhere.

2021-02-23 17:20 UTC, waehlisch requested changes
copying remark from #13: all these steps are replicated from the deployment job (deployment.yml). this replication is error-prone when changes occur. it would be better to re-use the definition of steps, i.e., define the steps once and use them multiple times.

@miri64 wrote that this is only possible by using external tooling.

i'm wondering why we don't move the run commands into an external script (see https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)

2021-02-23 17:21 UTC, miri64 commented
> i'm wondering why we don't move the run commands into an external script (see https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)

That would require another repo. But I would prefer a simple shell script within the base repo that does all the required steps in one go.

2021-02-23 17:24 UTC, aabadie commented
> But I would prefer a simple shell script within the base repo that does all the required steps in one go.

Is there a way to use Jekyll hooks and to not use the preprocessing steps in the CI ? That would also allow people tp build the website locally and check the rendering/content as it would be deployed.

2021-02-23 17:28 UTC, leandrolanzieri commented
> TBH for this kind of preview, I would prefer Circle CI artifacts.

Sure, I'm in favor of whatever makes things easier.

> Is there a way to use Jekyll hooks and to not use the preprocessing steps in the CI ? 

I'm not sure, would it imply that we create a jekyll plugin? https://jekyllrb.com/docs/plugins/hooks/

2021-02-23 17:28 UTC, miri64 commented
> > But I would prefer a simple shell script within the base repo that does all the required steps in one go.
> 
> Is there a way to use Jekyll hooks and to not use the preprocessing steps in the CI ? That would also allow people tp build the website locally and check the rendering/content as it would be deployed. That would also allow to remove the boards/cpu yml config files commited in the repo.

If there are hooks to ... hook into in Jekyll, all the better IMHO, the problem was for the RIOT repo to be required for that, right? Maybe that can just be supplied via an environment variable, like we did for the release-specs tests?

2021-02-23 17:29 UTC, aabadie commented
> Sadly we will not be getting this nice comment in PRs coming from forked repos

So that means that the preview won't be available in this case (PR from external forks, which is a must have TBH) ? We have documentation preview for RIOT using the CircleCI artifacts and that works for this case.

Maybe that would be doable this way ? (but again the build workflow must be fixed/simplified first, repeating myself just in case)

2021-02-23 17:30 UTC, aabadie commented
> the problem was for the RIOT repo to be required for that, right? 

Use a submodule ?

2021-02-23 17:33 UTC, leandrolanzieri commented
> > Sadly we will not be getting this nice comment in PRs coming from forked repos
> 
> So that means that the preview won't be available in this case (PR from external forks, which is a must have TBH) ? We have documentation preview for RIOT using the CircleCI artifacts and that works for this case.

This is a limitation of the action, the preview is deployed but no comment with the URL is added. That's why I added the comment step. I'll take a look at the CircleCI integration

2021-02-23 17:35 UTC, aabadie commented
> I'll take a look at the CircleCI integration

You need to fix the build workflow first: make it simple, one-line command (maybe use a Makefile ?, with one target for the preview). Call this one-liner from a single step in the deploy gh action. Once you have that, you can work with circleci.

2021-02-23 17:43 UTC, miri64 commented
> > the problem was for the RIOT repo to be required for that, right?
> 
> Use a submodule ?

Why restrict to a specific version of RIOT?

2021-02-23 17:44 UTC, miri64 commented
Seriously, I think with having a environment variable like `RIOTBASE` we will have much more flexibility (and also could use the same approach for the actual deployment).

2021-02-23 17:47 UTC, aabadie commented
> Why restrict to a specific version of RIOT?

If the submodule points to the master branch of RIOT and is updated by the build workflow, the version used will be the latest one used during the build. Then configure a scheduled trigger in the deploy action and the website is updated automatically, the same.

2021-02-23 18:01 UTC, miri64 commented
> If the submodule points to the master branch of RIOT and is updated by the build workflow, the version used to generate the website will be the latest one.

AFAIK submodules only can point to a specific version, no the HEAD of a branch, because Git internally they are just a file containing the commit hash. Might be that they changed that, but https://git-scm.com/docs/git-submodule doesn't say anything about it. As such, a submodule would mean that we have to change the head of that submodule in this repo from time to time (regardless of the updates in action or local builds) otherwise it will get outdated after a while, increasing build (or rather download) time. Basically the same as we currently do for applications, Tutorials, etc... and there it already works only marginally good. ;-).

2021-02-23 18:04 UTC, aabadie commented
> submodules only can point to a specific version, no the HEAD of a branch, because Git internally they are just a file containing the commit hash

Hmm, yeah that's true. I don't know what I had in mind. So just cloning RIOT in a subfolder and update it during the build is enough.

2021-02-23 18:07 UTC, miri64 commented
> So just cloning RIOT in a subfolder and update it during the build is enough.

Or assume (like in other repos of ours) that RIOT is already checked out at `../RIOT`, set that to an overridable variable and use that. Alternatively the user can overwrite that then and even if RIOT is not there, we could use some sensible defaults for the data generated from the repo (like it is the case now).

2021-02-23 18:13 UTC, waehlisch commented
> Or assume (like in other repos of ours) that RIOT is already checked out at `../RIOT`, set that to an overridable variable and use that. Alternatively the user can overwrite that then and even if RIOT is not there, we could use some sensible defaults for the data generated from the repo (like it is the case now).

a self-consistent solution is preferred. by default, you should not assume that the RIOT code is already stored locally when you edit the website.

2021-02-23 19:08 UTC, miri64 commented
> a self-consistent solution is preferred. by default, you should not assume that the RIOT code is already stored locally when you edit the website.

That's why I was proposing the fallback to a default.

But even then it's not like this isn't a workflow we use already everywhere else when it comes to compiling RIOT itself. I think it's reasonable to assume that someone who wants to change the RIOT website and they care about accurate numbers in their local checkout, that they have already some version of RIOT lying around somewhere.

2021-02-23 19:17 UTC, waehlisch commented
>  I think it's reasonable to assume that someone who wants to change the RIOT website and they care about accurate numbers in their local checkout, that they have already some version of RIOT lying around somewhere.

no necessarily. ... anyhow, multiple questions: (1) whether a user cares about accurate numbers, (2) whether you can assume the code base is already available.

2021-02-23 19:26 UTC, miri64 commented
> (1) whether a user cares about accurate numbers, (2) whether you can assume the code base is already available.

If both (1) and (2) are false, we can fallback to an appropriate default. If (1) is true the RIOT source needs to be provided somehow, either by the user or by us. If (2) is true we don't need to provide the RIOT source (but we may).

The problem with (2) being false, but (1) being true and we would go for submodules is that this would provide us with a maintenance burden, just to keep the build/fetch time of the website low. On the other hand with (1) and (2) being true, we don't have any control over the accuracy of the numbers, since than the website developer needs to take care of checking out the current master of RIOT themselves (vs. less scripting complexity for us)

2021-02-23 19:27 UTC, miri64 commented
Should we maybe take this discussion somewhere else, because this becomes more and more about how to streamline the building of the website, rather than automated tests of PRs, what this PR is about.

2021-02-25 10:38 UTC, leandrolanzieri commented
The update of RIOT-related data has been refactored. One can use `make` targets to update stats, boards and contributors so far. If no `RIOTBASE` is defined, the repo is cloned locally. I added instructions in the `README`.

2021-02-25 13:30 UTC, jia200x commented
I added a tool for parsing drivers from the RIOT repo and some make commands (`make build`, `make serve`)

2021-02-25 15:00 UTC, aabadie commented
> I added a tool for parsing drivers from the RIOT repo and some make commands (make build, make serve)

Nice but can we split these changes in a separate PR ?

2021-02-25 15:17 UTC, jia200x commented
> > I added a tool for parsing drivers from the RIOT repo and some make commands (make build, make serve)
> 
> Nice but can we split these changes in a separate PR ?

See https://github.com/RIOT-OS/riot-os.org/pull/17

2021-03-02 09:03 UTC, waehlisch commented
@leandrolanzieri can you update based on #17 ?

2021-03-02 09:04 UTC, jia200x commented
this should be rebased now

2021-03-02 09:33 UTC, leandrolanzieri commented
Rebased, let's see how everything works with the refactor

2021-03-02 09:52 UTC, leandrolanzieri commented
BTW I changed the PR to invoke surge directly, instead of using an action, given that it had the limitation on forked repos.

2021-03-02 10:11 UTC, miri64 commented
Works and https://github.com/RIOT-OS/riot-os.org/pull/15#issuecomment-785794413 was updated. *thinks about using the comment action for the release tests to reduce spam*...

2021-03-02 10:36 UTC, waehlisch approved these changes

2021-03-02 10:36 UTC, merged

2021-03-02 10:36 UTC, leandrolanzieri commented on README.md
> +contributors board list, etc) is parsed from files in the `_data` folder. To
The README is no longer modified in this PR, it was already updated in #17